on:
  push:
    branches: [ master ]
  pull_request:

name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Cargo clippy
        working-directory: rust
        run: cargo clippy --all-targets --all-features --examples
