on:
  push:
    branches: [ master ]
  pull_request:

name: Code formatting check

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Cargo fmt
        working-directory: rust
        run: cargo fmt --all -- --check
